import json

from tools.parse_transcripts import (
    find_agent_files,
    link_agent_ids_via_meta,
    parse_transcript,
    read_jsonl,
    summarize_for_index,
    summarize_tool_result,
    summarize_tool_use,
)


def line(**kw):
    base = {"timestamp": "2026-01-01T00:00:00.000Z", "gitBranch": "main", "cwd": "/Users/drmaciver/Projects/autoroad"}
    base.update(kw)
    return base


def user_text(text, ts="2026-01-01T00:00:00.000Z"):
    return line(type="user", timestamp=ts, message={"role": "user", "content": text})


def assistant_block(block, ts="2026-01-01T00:00:01.000Z"):
    return line(type="assistant", timestamp=ts, message={"role": "assistant", "content": [block]})


def tool_result_line(tool_use_id, content, tur=None, ts="2026-01-01T00:00:02.000Z"):
    d = line(
        type="user",
        timestamp=ts,
        message={
            "role": "user",
            "content": [{"type": "tool_result", "tool_use_id": tool_use_id, "content": content}],
        },
    )
    if tur is not None:
        d["toolUseResult"] = tur
    return d


def test_basic_turn_alternation_and_grouping():
    lines = [
        user_text("Hello, please list files."),
        assistant_block({"type": "thinking", "thinking": "let's look"}),
        assistant_block({"type": "text", "text": "I'll list them."}),
        assistant_block(
            {
                "type": "tool_use",
                "id": "tu1",
                "name": "Bash",
                "input": {"command": "ls -la", "description": "List files"},
            }
        ),
        tool_result_line("tu1", [{"type": "text", "text": "total 0\nfile.txt", "is_error": False}]),
        user_text("Thanks, now write a poem."),
        assistant_block({"type": "text", "text": "Roses are red."}),
    ]
    parsed = parse_transcript("sess1", lines)
    assert [t.role for t in parsed.turns] == ["user", "assistant", "user", "assistant"]

    assistant_turn = parsed.turns[1]
    kinds = [b["kind"] for b in assistant_turn.blocks]
    assert kinds == ["thinking", "text", "tool_use", "tool_result"]
    assert assistant_turn.blocks[2]["tool"] == "Bash"
    assert assistant_turn.blocks[2]["command"] == "ls -la"
    assert assistant_turn.blocks[3]["status"] == "ok"

    assert parsed.start == "2026-01-01T00:00:00.000Z"
    assert parsed.end == "2026-01-01T00:00:02.000Z"
    assert parsed.git_branch == "main"


def test_local_command_caveat_dropped_and_command_name_becomes_command_block():
    caveat = "<local-command-caveat>Caveat: The messages below were generated by the user while running local commands. DO NOT respond to these messages or otherwise consider them in your response unless the user explicitly asks you to.</local-command-caveat>"
    cmd = "<command-name>/clear</command-name>\n            <command-message>clear</command-message>\n            <command-args></command-args>"
    lines = [user_text(caveat), user_text(cmd)]
    parsed = parse_transcript("sess2", lines)
    assert len(parsed.turns) == 1
    assert parsed.turns[0].blocks == [{"kind": "command", "name": "/clear"}]


def test_read_edit_write_tool_use_only_keeps_relative_path():
    block = summarize_tool_use(
        "Read", {"file_path": "/Users/drmaciver/Projects/autoroad/notes/voices.md"}, {}
    )
    assert block == {"kind": "tool_use", "tool": "Read", "file": "notes/voices.md"}
    assert "content" not in block


def test_read_tool_use_never_leaks_content_field():
    # simulate a maliciously-shaped input to make sure nothing but file_path survives
    block = summarize_tool_use(
        "Write",
        {"file_path": "/Users/drmaciver/Projects/autoroad/x.md", "content": "SPOILER TEXT"},
        {},
    )
    assert "SPOILER TEXT" not in json.dumps(block)


def test_bash_tool_use_truncated_and_has_description():
    long_cmd = "echo " + "a" * 300
    block = summarize_tool_use("Bash", {"command": long_cmd, "description": "print"}, {})
    assert len(block["command"]) <= 201
    assert block["description"] == "print"


def test_agent_tool_use_fields():
    block = summarize_tool_use(
        "Agent",
        {
            "description": "Fold decisions",
            "subagent_type": "general-purpose",
            "prompt": "x" * 500,
            "model": "opus",
        },
        {},
    )
    assert block["description"] == "Fold decisions"
    assert block["subagent_type"] == "general-purpose"
    assert block["model"] == "opus"
    assert len(block["prompt"]) <= 301


def test_workflow_tool_use_parses_meta_and_counts_agent_calls():
    script = """
export const meta = {
  name: 'my-workflow',
  description: 'does a thing',
  phases: [],
}
await agent('do x')
await parallel([() => agent('a'), () => agent('b')])
"""
    block = summarize_tool_use("Workflow", {"script": script}, {})
    assert block["workflow_name"] == "my-workflow"
    assert block["workflow_description"] == "does a thing"
    assert block["agent_call_count"] == 3


def test_grep_glob_pattern_and_web_fields():
    assert summarize_tool_use("Grep", {"pattern": "foo.*bar"}, {})["pattern"] == "foo.*bar"
    assert summarize_tool_use("WebFetch", {"url": "https://x.test"}, {})["url"] == "https://x.test"
    assert summarize_tool_use("WebSearch", {"query": "royal road style"}, {})["query"] == "royal road style"


def test_other_tool_falls_back_to_truncated_json_input():
    block = summarize_tool_use("SomeWeirdTool", {"a": 1, "b": "x" * 300}, {})
    assert block["tool"] == "SomeWeirdTool"
    assert len(block["input"]) <= 201


def test_bash_result_keeps_short_stdout_preview():
    tool_use_index = {"tu1": {"name": "Bash", "input": {"command": "ls"}}}
    block = summarize_tool_result(
        "tu1",
        [{"type": "text", "text": "a\nb", "is_error": False}],
        {"stdout": "a\nb\nc\nd", "stderr": "", "interrupted": False},
        tool_use_index,
    )
    assert block["status"] == "ok"
    assert block["stdout_preview"] == ["a", "b", "c"]


def test_bash_result_suppresses_cat_like_output():
    tool_use_index = {"tu1": {"name": "Bash", "input": {"command": "cat notes/canon/peri.md"}}}
    block = summarize_tool_result(
        "tu1",
        [{"type": "text", "text": "SPOILER FILE CONTENTS", "is_error": False}],
        {"stdout": "SPOILER FILE CONTENTS", "stderr": "", "interrupted": False},
        tool_use_index,
    )
    assert "stdout_preview" not in block
    assert "SPOILER" not in json.dumps(block)
    # size is still reported
    assert block["size"]["chars"] > 0


def test_error_tool_result_truncated_and_flagged():
    tool_use_index = {}
    block = summarize_tool_result(
        "tu2",
        {"type": "text", "text": "boom " * 100, "is_error": True},
        None,
        tool_use_index,
    )
    assert block["status"] == "error"
    assert len(block["error"]) <= 201


def test_agent_link_via_tool_use_result(tmp_path):
    lines = [
        user_text("go do a subtask"),
        assistant_block(
            {
                "type": "tool_use",
                "id": "tu_agent",
                "name": "Agent",
                "input": {"description": "d", "subagent_type": "general-purpose", "prompt": "p"},
            }
        ),
        tool_result_line(
            "tu_agent",
            [{"type": "text", "text": "launched"}],
            tur={"agentId": "aXYZ", "status": "async_launched"},
        ),
    ]
    parsed = parse_transcript("sess3", lines)
    from tools.parse_transcripts import annotate_agent_and_workflow_links

    annotate_agent_and_workflow_links(parsed)
    tool_use_block = parsed.turns[1].blocks[0]
    assert tool_use_block["subagent_id"] == "aXYZ"


def test_workflow_link_via_run_id():
    lines = [
        user_text("kick off a workflow"),
        assistant_block(
            {
                "type": "tool_use",
                "id": "tu_wf",
                "name": "Workflow",
                "input": {"script": "export const meta = {name:'x',description:'y',phases:[]}"},
            }
        ),
        tool_result_line("tu_wf", [{"type": "text", "text": "launched"}], tur={"runId": "wf_abc"}),
    ]
    parsed = parse_transcript("sess4", lines)
    from tools.parse_transcripts import annotate_agent_and_workflow_links

    annotate_agent_and_workflow_links(parsed)
    tool_use_block = parsed.turns[1].blocks[0]
    assert tool_use_block["workflow_run_id"] == "wf_abc"


def test_find_agent_files_discovers_top_level_and_nested_workflow_agents(tmp_path):
    session_dir = tmp_path / "sess5"
    (session_dir / "subagents").mkdir(parents=True)
    (session_dir / "subagents" / "agent-a111.jsonl").write_text("{}\n")
    (session_dir / "subagents" / "agent-a111.meta.json").write_text(
        json.dumps({"agentType": "general-purpose", "toolUseId": "tu_agent"})
    )
    wf_dir = session_dir / "subagents" / "workflows" / "wf_abc"
    wf_dir.mkdir(parents=True)
    (wf_dir / "agent-a222.jsonl").write_text("{}\n")
    (wf_dir / "agent-a222.meta.json").write_text(json.dumps({"agentType": "workflow-subagent"}))

    files = find_agent_files(session_dir)
    assert set(files.keys()) == {"a111", "a222"}
    assert files["a111"]["workflow_run_id"] is None
    assert files["a222"]["workflow_run_id"] == "wf_abc"


def test_link_agent_ids_via_meta_fallback(tmp_path):
    session_dir = tmp_path / "sess6"
    (session_dir / "subagents").mkdir(parents=True)
    (session_dir / "subagents" / "agent-aFB.jsonl").write_text("{}\n")
    (session_dir / "subagents" / "agent-aFB.meta.json").write_text(
        json.dumps({"agentType": "general-purpose", "toolUseId": "tu_no_result"})
    )
    lines = [
        user_text("go"),
        assistant_block(
            {
                "type": "tool_use",
                "id": "tu_no_result",
                "name": "Agent",
                "input": {"description": "d", "subagent_type": "general-purpose", "prompt": "p"},
            }
        ),
        # no matching tool_result at all -> must fall back to meta.json scan
    ]
    parsed = parse_transcript("sess6", lines)
    agent_files = find_agent_files(session_dir)
    link_agent_ids_via_meta(parsed, agent_files)
    assert {"tool_use_id": "tu_no_result", "agent_id": "aFB"} in parsed.agent_links


def test_summarize_for_index_counts_user_turns_and_tools():
    lines = [
        user_text("first prompt " + "x" * 400),
        assistant_block({"type": "tool_use", "id": "t1", "name": "Bash", "input": {"command": "ls"}}),
        tool_result_line("t1", [{"type": "text", "text": "ok"}]),
        user_text("second"),
    ]
    parsed = parse_transcript("sess7", lines)
    entry = summarize_for_index(parsed, has_subagents=True)
    assert entry["user_turns"] == 2
    assert entry["tool_counts"] == {"Bash": 1}
    assert entry["has_subagents"] is True
    assert len(entry["first_user_prompt"]) <= 301
    assert entry["first_user_prompt"].startswith("first prompt")


def test_read_jsonl_skips_blank_and_malformed_lines(tmp_path):
    p = tmp_path / "x.jsonl"
    p.write_text('{"a": 1}\n\n not json \n{"b": 2}\n')
    out = list(read_jsonl(p))
    assert out == [{"a": 1}, {"b": 2}]
